name: Auto-format to Google Style Guide

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
          github-token: ${{ secrets.GITHUB_TOKEN }}